### ISSUE TITLE
Issue with running it

### ISSUE THREAD

**Issue by nerd-bear** [HavenSelph/ruse#3]
Does not run with Tetris OS!!
This is a major compatibility issue that needs to be addressed!!!
PLS fix!!

**Comment by KastienDevOp** [comment]
Doesn't run on my Tamagachi either! Please Help!

**Comment by andreaslam** [comment]
SEV 1 issue needs to run doom

**Comment by mustafaquraish** [comment]
Fixed in #1, empty code runs in every environment

**Comment by andreaslam** [comment]
thx

**Comment by nerd-bear** [comment]
Needs update to support Washing Machine from Bosh
